In [1]:
import numpy as np
import scipy.optimize as opt

# 3.1
次の関数の勾配とヘッセ行列を求めよ.

(i)
>$$f(x) = 2 x_1^3 - x_1^2x_2 + 2x_2^2.$$

$$
\nabla f(x) = \begin{bmatrix}
                6 x_1^2 - 2x_1x_2\\
                -x_1^2 + 4x_2
              \end{bmatrix},\ 
\nabla^2 f(x) = \begin{bmatrix}
                  12x_1 - 2x_2  &  -2x_1\\
                  -2x_1  & 4
                \end{bmatrix}.
$$

In [2]:
# 最適解なし
f = lambda x: 2*(x[0]**3) - (x[0]**2)*x[1] + 2*(x[1]**2)
x0 = np.array([1.0, 1.0])
res = opt.minimize(f, x0, method="nelder-mead", options={"disp": True})

In [3]:
# methodを指定しないと嘘解が求まっちゃう
res = opt.minimize(f, x0, options={"disp": True})
res.x

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 14
         Function evaluations: 48
         Gradient evaluations: 16


array([ 8.47274610e-04, -7.46373369e-09])

(ii)
>$$ f(x) = (x_1 - 3)^2 + x_1 x_2 + \frac{1}{16}x_2^4 + (x_2 - 1)^2. $$

$$
    \nabla f(x) = \begin{bmatrix}
                    2x_1 + x_2 - 6 \\
                    x_1 + \frac{1}{4} x_2^3 + 2x_2 - 2
                  \end{bmatrix},\ 
    \nabla^2 f(x) = \begin{bmatrix}
                      2 & 1\\
                      1 & \frac{3}{4}x_2^2 + 2
                    \end{bmatrix}.
$$

In [4]:
f = lambda x: (x[0]-3)**2 + x[0]*x[1] + (1/16)*(x[1]**4) + (x[1]-1)**2
x0 = np.array([1.0, 1.0])
res = opt.minimize(f, x0, method="nelder-mead", options={"disp": True})
res.x

Optimization terminated successfully.
         Current function value: 0.677505
         Iterations: 46
         Function evaluations: 88


array([ 3.3128884 , -0.62579102])

In [5]:
# 勾配を指定して BFGS を使った方が収束が早い.
def jac(x):
    output = np.zeros(2)
    output[0] = 2*x[0] + x[1] - 6
    output[1] = x[0] + (1/4)*(x[1]**3) + 2*x[1] - 2
    return output

res = opt.minimize(f, x0, method="BFGS", jac=jac, options={"disp": True})
res.x

Optimization terminated successfully.
         Current function value: 0.677505
         Iterations: 7
         Function evaluations: 8
         Gradient evaluations: 8


array([ 3.31290812, -0.6258167 ])

# 3.2
>正定値対称行列 $A = (A_{ij}) \in \mathbb{R}^{n\times n}$, ベクトル $b \in \mathbb{R}^n$ に対し, 連立1次方程式
>$$ Ax = b \tag{3.32} $$
>の解と無制約最適化問題
>$$ \min f(x) = \frac{1}{2}x'Ax - b'x  \tag{3.33} $$
>の解が一致することを示せ. また, $\nabla^2 f(x) = A$ を示せ.

$f(x)$ の勾配およびヘッセ行列は,
$$
    \nabla f(x) = Ax - b,\ \nabla^2 f(x) = A
$$
であり, $A$ は正定値行列なので $f$ は狭義凸関数. したがって, $x^*$ が (3.33) の最適解であることの必要十分条件は,
$$
    \nabla f(x^*) = A x^* - b = 0
$$
である.